### PR TITLE
Fixed issue for get when key doesn't exist and json option is true

### PR DESCRIPTION
**Pull request by JoeDoyle23**
Discovered an issue when using the new json option on get and the key doesn't exist. Fixed the bug and added a test for it.

### CODE REVIEW

**Comment by mafintosh** [comment]
should i release this as a patch?

**Comment by JoeDoyle23** [comment]
Yes, please. I would have but I can't push it to npm.

**Comment by mafintosh** [comment]
@JoeDoyle23 whats your npm username?

**Comment by mafintosh** [comment]
Released in 2.4.1

**Comment by JoeDoyle23** [comment]
Same as GitHub, joedoyle23.

**Comment by mafintosh** [comment]
added on npm as well now

**Comment by JoeDoyle23** [comment]
Great! Thanks!

**Pull request merged**
